/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Income {
  'id' : string,
  'date' : string,
  'note' : [] | [string],
  'category' : string,
  'amount' : number,
}
export interface Receipt {
  'id' : string,
  'subCategory' : string,
  'date' : string,
  'note' : [] | [string],
  'amount' : number,
  'mainCategory' : string,
}
export interface _SERVICE {
  'addIncomeEntry' : ActorMethod<
    [number, string, string, [] | [string]],
    string
  >,
  'addNote' : ActorMethod<[string, string], undefined>,
  'addReceiptEntry' : ActorMethod<
    [number, string, string, string, [] | [string]],
    string
  >,
  'deleteIncomeEntry' : ActorMethod<[string], undefined>,
  'deleteReceiptEntry' : ActorMethod<[string], undefined>,
  'getAllChecklistStates' : ActorMethod<
    [],
    Array<[string, Array<[string, boolean]>]>
  >,
  'getAllIncomeEntries' : ActorMethod<[], Array<Income>>,
  'getAllNotes' : ActorMethod<[], Array<[string, string]>>,
  'getAllReceiptEntries' : ActorMethod<[], Array<Receipt>>,
  'getCheckingBalance' : ActorMethod<[], number>,
  'getFinancialOverview' : ActorMethod<
    [],
    {
      'housingFund' : number,
      'savingsAmount' : number,
      'checkingBalance' : number,
    }
  >,
  'getFinancialSummary' : ActorMethod<
    [],
    {
      'totalIncome' : number,
      'housingFund' : number,
      'totalBills' : number,
      'savingsAmount' : number,
      'totalHouseholdGoods' : number,
      'checkingBalance' : number,
    }
  >,
  'getGrocerySpending' : ActorMethod<[string], number>,
  'getHousingFund' : ActorMethod<[], number>,
  'getMonthlyIncomeTotal' : ActorMethod<[string], number>,
  'getMonthlyReceiptTotal' : ActorMethod<[string], number>,
  'getNonEssentialSpending' : ActorMethod<[string], number>,
  'getNote' : ActorMethod<[string], [] | [string]>,
  'getSavingsAmount' : ActorMethod<[], number>,
  'getTotalBills' : ActorMethod<[], number>,
  'getTotalHouseholdGoods' : ActorMethod<[], number>,
  'getTotalIncome' : ActorMethod<[], number>,
  'getWeeklyReceiptTotal' : ActorMethod<[string], number>,
  'toggleChecklistItem' : ActorMethod<[string, string], boolean>,
  'updateCheckingBalance' : ActorMethod<[number], undefined>,
  'updateGrocerySpending' : ActorMethod<[string, number], undefined>,
  'updateHousingFund' : ActorMethod<[number], undefined>,
  'updateNonEssentialSpending' : ActorMethod<[string, number], undefined>,
  'updateReceiptCategory' : ActorMethod<[string, string, string], undefined>,
  'updateSavingsAmount' : ActorMethod<[number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];