/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Income = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Receipt = IDL.Record({
  'id' : IDL.Text,
  'subCategory' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
  'mainCategory' : IDL.Text,
});

export const idlService = IDL.Service({
  'addIncomeEntry' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'addNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addReceiptEntry' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteIncomeEntry' : IDL.Func([IDL.Text], [], []),
  'deleteReceiptEntry' : IDL.Func([IDL.Text], [], []),
  'getAllChecklistStates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))))],
      ['query'],
    ),
  'getAllIncomeEntries' : IDL.Func([], [IDL.Vec(Income)], ['query']),
  'getAllNotes' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllReceiptEntries' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
  'getCheckingBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getFinancialOverview' : IDL.Func(
      [],
      [
        IDL.Record({
          'housingFund' : IDL.Float64,
          'savingsAmount' : IDL.Float64,
          'checkingBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getFinancialSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalIncome' : IDL.Float64,
          'housingFund' : IDL.Float64,
          'totalBills' : IDL.Float64,
          'savingsAmount' : IDL.Float64,
          'totalHouseholdGoods' : IDL.Float64,
          'checkingBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getGrocerySpending' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getHousingFund' : IDL.Func([], [IDL.Float64], ['query']),
  'getMonthlyIncomeTotal' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getMonthlyReceiptTotal' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getNonEssentialSpending' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getNote' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getSavingsAmount' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalBills' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalHouseholdGoods' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalIncome' : IDL.Func([], [IDL.Float64], ['query']),
  'getWeeklyReceiptTotal' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'toggleChecklistItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateCheckingBalance' : IDL.Func([IDL.Float64], [], []),
  'updateGrocerySpending' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateHousingFund' : IDL.Func([IDL.Float64], [], []),
  'updateNonEssentialSpending' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateReceiptCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSavingsAmount' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Income = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Receipt = IDL.Record({
    'id' : IDL.Text,
    'subCategory' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
    'mainCategory' : IDL.Text,
  });
  
  return IDL.Service({
    'addIncomeEntry' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'addNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addReceiptEntry' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteIncomeEntry' : IDL.Func([IDL.Text], [], []),
    'deleteReceiptEntry' : IDL.Func([IDL.Text], [], []),
    'getAllChecklistStates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))))],
        ['query'],
      ),
    'getAllIncomeEntries' : IDL.Func([], [IDL.Vec(Income)], ['query']),
    'getAllNotes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllReceiptEntries' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
    'getCheckingBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getFinancialOverview' : IDL.Func(
        [],
        [
          IDL.Record({
            'housingFund' : IDL.Float64,
            'savingsAmount' : IDL.Float64,
            'checkingBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getFinancialSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalIncome' : IDL.Float64,
            'housingFund' : IDL.Float64,
            'totalBills' : IDL.Float64,
            'savingsAmount' : IDL.Float64,
            'totalHouseholdGoods' : IDL.Float64,
            'checkingBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getGrocerySpending' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getHousingFund' : IDL.Func([], [IDL.Float64], ['query']),
    'getMonthlyIncomeTotal' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getMonthlyReceiptTotal' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getNonEssentialSpending' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getNote' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getSavingsAmount' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalBills' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalHouseholdGoods' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalIncome' : IDL.Func([], [IDL.Float64], ['query']),
    'getWeeklyReceiptTotal' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'toggleChecklistItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateCheckingBalance' : IDL.Func([IDL.Float64], [], []),
    'updateGrocerySpending' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateHousingFund' : IDL.Func([IDL.Float64], [], []),
    'updateNonEssentialSpending' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateReceiptCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateSavingsAmount' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };