/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Receipt {
    id: string;
    subCategory: string;
    accountId: string;
    date: string;
    note?: string;
    user: string;
    amount: number;
    mainCategory: string;
}
export interface Account {
    id: string;
    balance: number;
    name: string;
    accountType: string;
}
export interface Income {
    id: string;
    accountId: string;
    date: string;
    note?: string;
    user: string;
    category: string;
    amount: number;
}
export interface backendInterface {
    addAccount(name: string, accountType: string, initialBalance: number): Promise<string>;
    addIncomeEntry(amount: number, date: string, category: string, note: string | null, user: string, accountId: string): Promise<string>;
    addNote(week: string, note: string): Promise<void>;
    addReceiptEntry(amount: number, date: string, mainCategory: string, subCategory: string, note: string | null, user: string, accountId: string): Promise<string>;
    deleteAccount(id: string): Promise<void>;
    deleteIncomeEntry(id: string): Promise<void>;
    deleteReceiptEntry(id: string): Promise<void>;
    getAccount(id: string): Promise<Account | null>;
    getAllAccounts(): Promise<Array<Account>>;
    getAllChecklistStates(): Promise<Array<[string, Array<[string, boolean]>]>>;
    getAllIncomeEntries(): Promise<Array<Income>>;
    getAllNotes(): Promise<Array<[string, string]>>;
    getAllReceiptEntries(): Promise<Array<Receipt>>;
    getFinancialOverview(): Promise<{
        housingFund: number;
        savingsAmount: number;
    }>;
    getFinancialSummary(): Promise<{
        totalIncome: number;
        housingFund: number;
        totalBills: number;
        savingsAmount: number;
        totalHouseholdGoods: number;
    }>;
    getFinancialSummaryByUser(user: string): Promise<{
        totalIncome: number;
        totalBills: number;
        totalHouseholdGoods: number;
    }>;
    getGrocerySpending(week: string): Promise<number>;
    getHousingFund(): Promise<number>;
    getIncomeEntriesByUser(user: string): Promise<Array<Income>>;
    getMonthlyIncomeTotal(month: string): Promise<number>;
    getMonthlyReceiptTotal(month: string): Promise<number>;
    getNonEssentialSpending(week: string): Promise<number>;
    getNote(week: string): Promise<string | null>;
    getReceiptEntriesByUser(user: string): Promise<Array<Receipt>>;
    getSavingsAmount(): Promise<number>;
    getTotalBills(): Promise<number>;
    getTotalHouseholdGoods(): Promise<number>;
    getTotalIncome(): Promise<number>;
    getWeeklyReceiptTotal(week: string): Promise<number>;
    toggleChecklistItem(group: string, item: string): Promise<boolean>;
    updateAccount(id: string, name: string, accountType: string, balance: number): Promise<void>;
    updateGrocerySpending(week: string, amount: number): Promise<void>;
    updateHousingFund(amount: number): Promise<void>;
    updateNonEssentialSpending(week: string, amount: number): Promise<void>;
    updateReceiptCategory(id: string, mainCategory: string, subCategory: string): Promise<void>;
    updateSavingsAmount(amount: number): Promise<void>;
}
import type { Account as _Account, Income as _Income, Receipt as _Receipt } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAccount(arg0: string, arg1: string, arg2: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccount(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccount(arg0, arg1, arg2);
            return result;
        }
    }
    async addIncomeEntry(arg0: number, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncomeEntry(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncomeEntry(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async addNote(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, arg1);
            return result;
        }
    }
    async addReceiptEntry(arg0: number, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReceiptEntry(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReceiptEntry(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async deleteAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount(arg0);
            return result;
        }
    }
    async deleteIncomeEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncomeEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncomeEntry(arg0);
            return result;
        }
    }
    async deleteReceiptEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReceiptEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReceiptEntry(arg0);
            return result;
        }
    }
    async getAccount(arg0: string): Promise<Account | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccount(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccount(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAccounts(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAccounts();
            return result;
        }
    }
    async getAllChecklistStates(): Promise<Array<[string, Array<[string, boolean]>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChecklistStates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChecklistStates();
            return result;
        }
    }
    async getAllIncomeEntries(): Promise<Array<Income>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncomeEntries();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncomeEntries();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotes(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return result;
        }
    }
    async getAllReceiptEntries(): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReceiptEntries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReceiptEntries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialOverview(): Promise<{
        housingFund: number;
        savingsAmount: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialOverview();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialOverview();
            return result;
        }
    }
    async getFinancialSummary(): Promise<{
        totalIncome: number;
        housingFund: number;
        totalBills: number;
        savingsAmount: number;
        totalHouseholdGoods: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialSummary();
            return result;
        }
    }
    async getFinancialSummaryByUser(arg0: string): Promise<{
        totalIncome: number;
        totalBills: number;
        totalHouseholdGoods: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialSummaryByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialSummaryByUser(arg0);
            return result;
        }
    }
    async getGrocerySpending(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrocerySpending(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrocerySpending(arg0);
            return result;
        }
    }
    async getHousingFund(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getHousingFund();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHousingFund();
            return result;
        }
    }
    async getIncomeEntriesByUser(arg0: string): Promise<Array<Income>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeEntriesByUser(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeEntriesByUser(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyIncomeTotal(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyIncomeTotal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyIncomeTotal(arg0);
            return result;
        }
    }
    async getMonthlyReceiptTotal(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReceiptTotal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReceiptTotal(arg0);
            return result;
        }
    }
    async getNonEssentialSpending(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getNonEssentialSpending(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNonEssentialSpending(arg0);
            return result;
        }
    }
    async getNote(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceiptEntriesByUser(arg0: string): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceiptEntriesByUser(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceiptEntriesByUser(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavingsAmount(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavingsAmount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavingsAmount();
            return result;
        }
    }
    async getTotalBills(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalBills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalBills();
            return result;
        }
    }
    async getTotalHouseholdGoods(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalHouseholdGoods();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalHouseholdGoods();
            return result;
        }
    }
    async getTotalIncome(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalIncome();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalIncome();
            return result;
        }
    }
    async getWeeklyReceiptTotal(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyReceiptTotal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyReceiptTotal(arg0);
            return result;
        }
    }
    async toggleChecklistItem(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChecklistItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChecklistItem(arg0, arg1);
            return result;
        }
    }
    async updateAccount(arg0: string, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateGrocerySpending(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGrocerySpending(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGrocerySpending(arg0, arg1);
            return result;
        }
    }
    async updateHousingFund(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHousingFund(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHousingFund(arg0);
            return result;
        }
    }
    async updateNonEssentialSpending(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNonEssentialSpending(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNonEssentialSpending(arg0, arg1);
            return result;
        }
    }
    async updateReceiptCategory(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReceiptCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReceiptCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSavingsAmount(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSavingsAmount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSavingsAmount(arg0);
            return result;
        }
    }
}
function from_candid_Income_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Income): Income {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Receipt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Receipt): Receipt {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    accountId: string;
    date: string;
    note: [] | [string];
    user: string;
    category: string;
    amount: number;
}): {
    id: string;
    accountId: string;
    date: string;
    note?: string;
    user: string;
    category: string;
    amount: number;
} {
    return {
        id: value.id,
        accountId: value.accountId,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.note)),
        user: value.user,
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subCategory: string;
    accountId: string;
    date: string;
    note: [] | [string];
    user: string;
    amount: number;
    mainCategory: string;
}): {
    id: string;
    subCategory: string;
    accountId: string;
    date: string;
    note?: string;
    user: string;
    amount: number;
    mainCategory: string;
} {
    return {
        id: value.id,
        subCategory: value.subCategory,
        accountId: value.accountId,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.note)),
        user: value.user,
        amount: value.amount,
        mainCategory: value.mainCategory
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Income>): Array<Income> {
    return value.map((x)=>from_candid_Income_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Receipt>): Array<Receipt> {
    return value.map((x)=>from_candid_Receipt_n8(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
